In [1]:
def area(int):
    x = int * int
    return x

In [2]:
print("area is", area(4))

area is 16


In [3]:
import numpy as np
    

In [4]:
array = np.arange(1,4)
print(array)

[1 2 3]


In [5]:
sample_array = np.array([1,2,3])
new_array = np.power(sample_array,4)
print(new_array)

[ 1 16 81]


In [6]:
multi_array = np.array([array, new_array])
print(multi_array)

[[ 1  2  3]
 [ 1 16 81]]


In [7]:
print(multi_array.shape)

(2, 3)


In [8]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [20]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [21]:
arr2 = np.random.randint(0,100,10)
arr2


array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [22]:
arr2.mean()

47.3

In [26]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [29]:
mat = np.arange(0,100).reshape(10,10)

In [30]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
row = 6
col = 9

mat[row,col]

69

In [46]:
mat[:6,9]
#uptil 6 rows, in 9th column, not including 69

array([ 9, 19, 29, 39, 49, 59])

In [34]:
 mat[:4, :4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [40]:
mat2 = mat[:, 1]

In [41]:
mat2.shape

(10,)

In [43]:
mat2


array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [45]:
mat2.reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [47]:
#making the entire selection chunk equal to zero
mat[:3,:3]=0
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])